### ISSUE TITLE
Panic in golangci-lint when tenv is enabled

### ISSUE THREAD

**Issue by anderseknert** [sivchari/tenv#25]
Not sure if this should be reported here, or in golangci-lint, but I'm sure you can advise me on that :) When I run tenv "standalone" on the [Open Policy Agent](https://github.com/open-policy-agent/opa) codebase it works as expected, but when included in golangci-lint I get a panic:

```
level=error msg="[runner] Panic: tenv: package \"test\" (isInitialPkg: true, needAnalyzeSource: true): runtime error: index out of range [0] with length 0: goroutine 14707 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x68\ngithub.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func1()\n\tgithub.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:101 +0x108\npanic({0xafebc0, 0x400130a588})\n\truntime/panic.go:838 +0x20c\ngithub.com/sivchari/tenv.targetRunner(0xa00?, {0x4000f36ce0, 0x19})\n\tgithub.com/sivchari/tenv@v1.5.0/tenv.go:158 +0x3f0\ngithub.com/sivchari/tenv.checkFunc(0x40016905c0?, 0x400bd6bec0, {0x4000f36ce0?, 0x1?})\n\tgithub.com/sivchari/tenv@v1.5.0/tenv.go:58 +0x38\ngithub.com/sivchari/tenv.run.func1({0xda80a0?, 0x40067e0e80})\n\tgithub.com/sivchari/tenv@v1.5.0/tenv.go:49 +0xf4\ngolang.org/x/tools/go/ast/inspector.(*Inspector).Preorder(0x400ca92a68, {0x4003cc6ce8?, 0x1?, 0xcf5d0?}, 0x400222fcf8)\n\tgolang.org/x/tools@v0.1.11-0.20220316014157-77aa08bb151a/go/ast/inspector/inspector.go:77 +0xac\ngithub.com/sivchari/tenv.run(0x40111528f0)\n\tgithub.com/sivchari/tenv@v1.5.0/tenv.go:40 +0x94\ngithub.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyze(0x4003296d90)\n\tgithub.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:187 +0x98c\ngithub.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func2()\n\tgithub.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:105 +0x24\ngithub.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0x4001a9b810, {0xb594fb, 0x4}, 0x4003d69730)\n\tgithub.com/golangci/golangci-lint/pkg/timeutils/stopwatch.go:111 +0x48\ngithub.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe(0x5593a0?)\n\tgithub.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:104 +0x78\ngithub.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze.func2(0x4003296d90)\n\tgithub.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_loadingpackage.go:80 +0xb4\ncreated by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze\n\tgithub.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_loadingpackage.go:75 +0x16c\n"
level=warning msg="[runner] Can't run linter goanalysis_metalinter: goanalysis_metalinter: tenv: package \"test\" (isInitialPkg: true, needAnalyzeSource: true): runtime error: index out of range [0] with length 0"
```

```shell
> go version 
go1.19.1 darwin/arm64
```

**Comment by anderseknert** [comment]
Ah, bumping golangci-lint version solved it. Sorry for the noise :)
